### ISSUE TITLE
Duplicate companies on portfolio page

### ISSUE THREAD

**Issue by maltsev** [Vivekkosare/vue-the-stock-trader#1]
I have been checking your app and noticed that the portfolio page is broken. I bought several different stocks, but the portfolio page lists only *BMW*:

![image](https://user-images.githubusercontent.com/923973/80504759-c3f3ca80-8973-11ea-91bc-1806803a3789.png)

**Comment by Vivekkosare** [comment]
Hi, Thanks for catching this error. I will fix this and again deploy it.

**Comment by Vivekkosare** [comment]
I have fixed the issue. Now stocks purchased from different companies are displayed in the portfolio section. It doesn't display BMW only.
![image](https://user-images.githubusercontent.com/41685006/85872608-46600580-b7d0-11ea-91b4-cd360421cafe.png)
